### PR TITLE
Issue-1602 Added test case for normalizing ORCID ids with and withou …

### PR DESCRIPTION
**Pull request by ashwinisukale**
…schemeURI

## Purpose

Added test case normalising ORCID ids with and without schemeURI

closes: https://github.com/datacite/datacite/issues/1602

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

- [ ] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Reviewer, please remember our [guidelines](https://datacite.atlassian.net/wiki/spaces/TEC/pages/1168375809/Pull+Request+Guidelines):

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure you give reasons for the changes you are proposing.

### CODE REVIEW

**Review by digitaldogsbody — APPROVED** [review]
Looks good.

It might be worth adding an additional test case for the original behaviour as well (i.e that the following identifier still comes out ok: `<nameIdentifier schemeURI="https://orcid.org/" nameIdentifierScheme="ORCID"> https://orcid.org/0000-0001-9998-0117 </nameIdentifier>`) but I don't consider this a blocker to merging :)

**Comment by ashwinisukale** [comment]
Thank you @digitaldogsbody :) for the review. I will add the test.

**Comment by ashwinisukale** [comment]
@digitaldogsbody while adding test case, I found one bug in our code, that if we have leading and trialing spaces in the ORCID id then we consider that id as invalid id, I have fixed the bug in the same PR. Could you please review this again.

```
<creator>
  <creatorName nameType="Personal">Mike B</creatorName>
  <nameIdentifier nameIdentifierScheme="ORCID"> 0000-0001-9998-0118 </nameIdentifier>
 </creator>
"  0000-0001-9998-0118  ",  # valid ORCID with leading/trailing spaces
```

**Comment by digitaldogsbody** [comment]
Great catch!

**Review by digitaldogsbody — APPROVED** [review]
:+1: let's get this rolled out and deployed to the services that use Bolognese

**Comment by ashwinisukale** [comment]
Let me change the gem version if we are going to deploy this change.

**Pull request merged**
